/**
 * Shared scrape → documentation pipeline for White Lab Studio.
 * Used by Cloudflare Pages Functions and the local dev server.
 */

const BLOCKED_HOSTS = new Set([
  "localhost",
  "127.0.0.1",
  "0.0.0.0",
  "[::1]",
  "metadata.google.internal",
]);

const MAX_MARKDOWN_CHARS = 120_000;

export function normalizeTargetUrl(raw) {
  if (typeof raw !== "string" || !raw.trim()) {
    throw new Error("URL is required.");
  }
  let parsed;
  try {
    parsed = new URL(raw.trim());
  } catch {
    throw new Error("Enter a valid URL (include https://).");
  }
  if (!["http:", "https:"].includes(parsed.protocol)) {
    throw new Error("Only http and https URLs are supported.");
  }
  const host = parsed.hostname.replace(/^\[|\]$/g, "");
  if (BLOCKED_HOSTS.has(host.toLowerCase())) {
    throw new Error("Local and internal URLs are not allowed.");
  }
  if (/^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(host)) {
    throw new Error("Private network URLs are not allowed.");
  }
  return parsed.toString();
}

function clipMarkdown(text) {
  if (!text) return "";
  const trimmed = text.trim();
  if (trimmed.length <= MAX_MARKDOWN_CHARS) return trimmed;
  return `${trimmed.slice(0, MAX_MARKDOWN_CHARS)}\n\n---\n\n*[Truncated for preview — full scrape may be shorter on export.]*`;
}

function extractTitle(markdown, fallbackUrl) {
  const line = markdown.split("\n").find((row) => row.startsWith("# "));
  if (line) return line.replace(/^#\s+/, "").trim();
  try {
    return new URL(fallbackUrl).hostname;
  } catch {
    return "Untitled page";
  }
}

function buildSummary(markdown) {
  const paragraphs = markdown
    .split("\n\n")
    .map((block) => block.trim())
    .filter((block) => block && !block.startsWith("#") && !block.startsWith("!["));
  const first = paragraphs[0] || "";
  return first.length > 320 ? `${first.slice(0, 317)}…` : first;
}

export function buildDocumentation({ url, markdown, template = "agency", provider = "jina" }) {
  const title = extractTitle(markdown, url);
  const summary = buildSummary(markdown);
  const stamp = new Date().toISOString();
  const host = new URL(url).hostname;

  const templates = {
    agency: "Client research brief generated for agency handoff. Review before external delivery.",
    technical: "Technical reference export for engineering and QA workflows.",
    freelancer: "Freelancer deliverable draft — edit, add pricing, and send to your client.",
  };
  const intro = templates[template] || templates.agency;

  return `# ${title}

> **Source:** ${url}  
> **Captured:** ${stamp}  
> **Host:** ${host}  
> **Engine:** White Lab Studio (${provider})  
> **Template:** ${template}

## Executive summary

${summary || "_No summary could be extracted automatically. Review the full capture below._"}

## Workflow note

${intro}

## Captured content

${markdown}

---

## Delivery checklist

- [ ] Verify facts and links against the live page
- [ ] Remove third-party branding if required by client contract
- [ ] Attach cover image export when presenting externally
- [ ] Store source URL for audit trail

_Generated by [White Lab Studio](https://whitelab.ltd/studio/) — testnet ecosystem tool._
`;
}

async function fetchJinaMarkdown(url) {
  const response = await fetch(`https://r.jina.ai/${encodeURI(url)}`, {
    headers: {
      Accept: "text/markdown",
      "User-Agent": "WhiteLab-Studio/1.0 (+https://whitelab.ltd/studio/)",
    },
  });
  if (!response.ok) {
    throw new Error(`Reader fallback failed (${response.status}). Try another URL or add FIRECRAWL_API_KEY.`);
  }
  return clipMarkdown(await response.text());
}

async function fetchFirecrawl(url, apiKey) {
  const response = await fetch("https://api.firecrawl.dev/v1/scrape", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      url,
      formats: ["markdown", "screenshot"],
      onlyMainContent: true,
    }),
  });

  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    const message = payload.error || payload.message || `Firecrawl error ${response.status}`;
    throw new Error(message);
  }

  const data = payload.data || {};
  return {
    markdown: clipMarkdown(data.markdown || ""),
    screenshot: data.screenshot || null,
    provider: "firecrawl",
  };
}

export async function scrapeToDocumentation(input, secrets = {}) {
  const url = normalizeTargetUrl(input.url);
  const template = input.template || "agency";
  const firecrawlKey = secrets.firecrawlApiKey || secrets.FIRECRAWL_API_KEY || "";

  let markdown = "";
  let screenshot = null;
  let provider = "jina";

  if (firecrawlKey) {
    try {
      const firecrawl = await fetchFirecrawl(url, firecrawlKey);
      markdown = firecrawl.markdown;
      screenshot = firecrawl.screenshot;
      provider = firecrawl.provider;
    } catch (error) {
      markdown = await fetchJinaMarkdown(url);
      provider = "jina-fallback";
      screenshot = null;
    }
  } else {
    markdown = await fetchJinaMarkdown(url);
  }

  if (!markdown) {
    throw new Error("No readable content returned for this URL.");
  }

  const title = extractTitle(markdown, url);
  const summary = buildSummary(markdown);
  const documentation = buildDocumentation({ url, markdown, template, provider });

  return {
    ok: true,
    url,
    title,
    summary,
    markdown,
    documentation,
    screenshot,
    provider,
    template,
    generatedAt: new Date().toISOString(),
  };
}
